spring:
  config:
    activate:
      on-profile: dev
    import: optional:application-secret.properties

  datasource:
    driver-class-name: ${DB_NAME_DEV}
    url: ${DB_URL_DEV}
    username: ${DB_USER_DEV}
    password: ${DB_PW_DEV}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        default_batch_fetch_size: 500
    open-in-view: false

  data:
    redis:
      host: redis
      port: 6379

kakao:
  client-id: ${KAKAO_ID}
  authorization-grant-type: authorization_code
  redirect-uri: ${KAKAO_REDIRECT_DEV}

server:
  address: 0.0.0.0

sentry:
  dsn: ${SENTRY_DSN}
  traces-sample-rate: 1.0
  exception-resolver-order: -2147483647

logging:
  discord:
    error-uri: ${DISCORD_ERROR_URI}
    business-1-uri: ${DISCORD_BUSINESS_1_URI}
    business-2-uri: ${DISCORD_BUSINESS_2_URI}
    business-3-uri: ${DISCORD_BUSINESS_3_URI}
  config: classpath:logback-dev.xml