spring:
  profiles:
    active: local

  servlet:
    multipart:
      enabled: true
      max-file-size: 3MB
      max-request-size: 5MB

jwt:
  secret: ${JWT_SECRET}

cloud:
  aws:
    credentials:
      accessKey: ${ACCESS_KEY}
      secretKey: ${SECRET_KEY}
      aws-region: ap-northeast-2
      s3-bucket-name: ${BUCKET_NAME}